on:
  graphql:
    url: https://api.producthunt.com/v2/api/graphql
    deduplicationKey: id
    itemsPath: data.posts.edges
    headers:
      Authorization: Bearer ${{secrets.PRODUCTHUNT_TOKEN}}
    query: |
      query {
        posts {
          edges{
            node {
              id
              commentsCount
              createdAt
              description
              featuredAt
              media {
                type
                url
                videoUrl
              }
              name
              productLinks {
                type
                url
              }
              user {
                name
                url
              }
              reviewsCount
              reviewsRating
              slug
              tagline
              url
              votesCount
              website
              topics {
                edges {
                  node {
                    name
                  }
                }
              }
              
            }
          }
        }
      }

    config:
      every: 15
      format: |
        const node = item.node;
        node.original_createdAt = node.createdAt;
        node.createdAt = new Date().toISOString()
        return node
      filterScript: |
        console.log('item.votesCount',item.votesCount)
        if(item.votesCount>=100){
          return true
        }
      outputsMode: combine
      exportOutputs: true
jobs:
  save:
    name: save to json
    runs-on: ubuntu-latest
    steps:
      - name: Create Hackernews JSON
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.graphql.outputs.path }}
        with:
          script: |
            const generateSources = require(`${process.env.GITHUB_WORKSPACE}/scripts/generate-ph-module.js`)
            await generateSources()
            return true
