on:
  reddit:
    url: https://www.reddit.com/r/stocks/top/
    # url: https://www.reddit.com/r/all/top/
    source: json
    config:
      # limit: 2
      # force: true
      outputsMode: combine
      filterScript: |
        delete item.all_awardings
        return item
    requestConfig:
      params:
        raw_json: 1
jobs:
  save:
    name: save to json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      # - uses: oleksiyrudenko/gha-git-credentials@v1
      #   with:
      #     token: "${{ secrets.GITHUB_TOKEN }}"
      # - name: pull to the latest
      #   run: git pull
      - name: Format message
        id: title
        uses: actions/github-script@v2
        with:
          script: |
            const outputs = ${{ toJSON(on.reddit.outputs) }}
            const titles = outputs.map((item,index)=>{
              return item.title
            }).join("\n");
            return {
              title: titles
            }
      - name: Translate to ZH
        id: translation
        uses: fabasoad/translation-action@main
        with:
          provider: microsoft
          api_key: ${{ secrets.MICROSOFT_TRANSLATE_API_KEY }}
          lang: "zh-Hans"
          api_additional_parameter: westus2
          source: ${{fromJSON(steps.title.outputs.result).title}}
      - name: Create Reddit JSON
        uses: actions/github-script@v2
        env:
          TEXT: ${{steps.translation.outputs.text}}
          OUTPUTS: ${{toJSON(on.reddit.outputs)}}
        with:
          script: |
            const path = require('path')
            const fsPure = require('fs')
            const fs = fsPure.promises
            const outputs = process.env.OUTPUTS;
            const items = JSON.parse(outputs)
            const titleStr = process.env.TEXT || "";
            const titleArray = titleStr.split('\n')
            console.log('titleArray',titleArray)
            return true
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v5
      #   with:
      #     message: "chore: add sources"
      #     add: "."
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy site
      #   uses: actionsflow/axios@v1
      #   with:
      #     url: ${{ secrets.VERCEL_HOOK }}
      #     method: "GET"
