on:
  reddit:
    url:
      - https://www.reddit.com/r/stocks/top/
      - https://www.reddit.com/r/investing/top/
      - https://www.reddit.com/r/wallstreetbets/top/
    # url: https://www.reddit.com/r/all/top/
    source: json
    config:
      # limit: 2
      # force: true
      every: "30 * * * *"
      outputsMode: combine
      exportOutputs: true
      filterScript: |
        if(item.subreddit==='wallstreetbets' && item.score<1000){
          return false
        }
        if(item.score>40){
          return true
        }

      format: |
        delete item.all_awardings
        item.original_created_utc = item.created_utc;
        item.created_utc = Math.floor(Date.now() / 1000);
        return item
    requestConfig:
      axios-retry:
        retries: 3
      params:
        raw_json: 1
jobs:
  saveredditstocks:
    name: save to json
    runs-on: ubuntu-latest
    steps:
      - name: Format reddit JSON
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        uses: ./.github/actions/format
        with:
          function: reddit
      - name: Create Reddit JSON
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        with:
          script: |
            const generateSources = require(`${process.env.GITHUB_WORKSPACE}/scripts/generate-reddit-top-module.js`)
            await generateSources({
              dest:"./data/reddit-stocks",
              name:"reddit-stocks"
            })
            return true
