on:
  reddit:
    url: https://www.reddit.com/r/all/top/.json?t=week
    source: json
    config:
      # limit: 2
      every: "33 8 * * *"
      force: true
      outputsMode: combine
      exportOutputs: true
      filterScript: |
        delete item.all_awardings
        return item
    requestConfig:
      params:
        raw_json: 1
jobs:
  save:
    name: save to json
    runs-on: ubuntu-latest
    steps:
      - name: Create Reddit JSON
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        with:
          script: |
            const generateSources = require(`${process.env.GITHUB_WORKSPACE}/scripts/generate-reddit-top-weekly-module.js`)
            await generateSources()
            return true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.0
        if: true
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: new item"
          branch: new-issue-item
          delete-branch: true
          title: New item update
