name: Actionsflow
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      include:
        description: "--include: workflow file filter, you can use glob format to filter your workflows, the default value is empty value, means no filter will be using"
        required: false
        default: ""
      force:
        description: "--force: whether force to run workflow, true or false"
        required: false
        default: "false"
      verbose:
        description: "--verbose: debug workflow, true or false"
        required: false
        default: "false"
  schedule:
    - cron: "*/5 * * * *"
  # push:
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - uses: actions/checkout@v2
      - name: Run Actionsflow
        uses: actionsflow/actionsflow-action@v1
        with:
          args: build --include ${{ github.event.inputs.include }} -f ${{github.event.inputs.force}} --verbose ${{github.event.inputs.verbose}}
          json-secrets: ${{ toJSON(secrets) }}
          json-github: ${{ toJSON(github) }}
      - name: Setup act
        uses: actionsflow/setup-act-for-actionsflow@v1
        with:
          version: 0.2.18
      - name: Run act
        continue-on-error: true
        run: act --workflows ./dist/workflows --secret-file ./dist/.secrets --eventpath ./dist/event.json --env-file ./dist/.env -P ubuntu-latest=actionsflow/act-environment:v1 -P ubuntu-18.04=actionsflow/act-environment:v1 --bind
      # - run: sleep 5
      # - run: ls -l
      # - run: git status
      # - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
      #   with:
      #     message: "chore: new item"
      #     push: false
      - name: chown
        run: sudo chown -R $USER:$USER ./
      - run: git status
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          labels: automerge
          commit-message: "chore: new item"
          branch: new-item
          delete-branch: true
          title: New item update
