name: Auto translate
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "i18n/i18next/zh/translation*.json"
  #     - "i18n/post-resource/en/*.json"
jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Translate
        uses: ./.github/actions/translate
        with:
          secret_id: ${{ secrets.TENCENT_TRANSLATION_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_TRANSLATION_SECRET_KEY }}
      - name: Sync to source
        uses: actions/github-script@v3
        with:
          script: |
            const syncResource = require(`${process.env.GITHUB_WORKSPACE}/scripts/sync-i18n-resource-module.js`)
            await syncResource()
            return true
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          labels: automerge
          commit-message: "chore: new translation"
          branch: i18n-auto-translation
          delete-branch: true
          title: New item update
