name: Auto translate
on:
  repository_dispatch:
    types:
      - new_item
  workflow_dispatch:
  # schedule:
  #   - cron: "29 * * * *"

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Translate
        uses: ./.github/actions/translate
        with:
          secret_id: ${{ secrets.TENCENT_TRANSLATION_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_TRANSLATION_SECRET_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: auto translation"
          branch: i18n-auto-translation
          delete-branch: true