name: Auto merge i18n
on:
  workflow_dispatch:
  pull_request_target:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        if: github.actor == 'theowenyoung' && (github.head_ref == 'i10n_main' || github.head_ref == 'i18n-auto-translation' || github.head_ref == 'new-item')
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          token: ${{ secrets.PERSONAL_TOKEN }}