name: Auto merge i18n
on:
  - pull_request_target
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        if: github.actor == 'theowenyoung' && github.head_ref == 'i10n_main'
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
