name: Auto translate
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "i18n/i18next/en/reddit-title*.json"
  #     - "i18n/i18next/en/reddit-excerpt*.json"
jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Translate
        uses: ./.github/actions/translate
        with:
          secret_id: ${{ secrets.TENCENT_TRANSLATION_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_TRANSLATION_SECRET_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: auto translation"
          branch: i18n-auto-translation
          delete-branch: true
          title: Auto translation
