name: Auto translate
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "45 */2 * * *"
  push:
    branches:
      - main
    paths:
      - "i18n/i18next/zh/translation*.json"
      - "i18n/post-resource/en/*.json"
jobs:
  auto-translate:
    runs-on: macos-latest
    steps:
      - name: Check is building
        uses: actions/github-script@v4
        id: shouldBuild
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const runed = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "auto-translate.yml",
            });
            const totalCount=runed.data.workflow_runs.filter(item=>item.status==="in_progress").length;
            console.log("totalCount",totalCount)
            console.log("runed",JSON.stringify(runed,null,2));
            return totalCount
          result-encoding: string
      - name: checkout
        if: steps.shouldBuild.outputs.result=='1'
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        if: steps.shouldBuild.outputs.result=='1'
        with:
          node-version: "12"
      - name: check files
        if: steps.shouldBuild.outputs.result=='1'
        uses: actions/github-script@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const syncResource = require(`${process.env.GITHUB_WORKSPACE}/scripts/translate-check-module.js`)
            await syncResource()
            return true
      - name: install puppeteer
        if: steps.shouldBuild.outputs.result=='1'
        run: npm i puppeteer
      - name: Translate
        if: steps.shouldBuild.outputs.result=='1'
        uses: ./.github/actions/translate
        continue-on-error: true
        with:
          provider: deepl
          secret_id: ${{ secrets.TENCENT_TRANSLATION_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_TRANSLATION_SECRET_KEY }}
      - name: Sync to source
        if: steps.shouldBuild.outputs.result=='1'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const syncResource = require(`${process.env.GITHUB_WORKSPACE}/scripts/sync-i18n-resource-module.js`)
            await syncResource()
            return true
      - name: git add
        if: steps.shouldBuild.outputs.result=='1'
        run: git add .
      - name: Create pull request
        if: steps.shouldBuild.outputs.result=='1'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          labels: automerge
          commit-message: "chore: new translation"
          branch: i18n-auto-translation
          delete-branch: true
          title: New item update
