name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "content/**"
      - "i18n/**"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Deploy site
        run: curl ${{ secrets.VERCEL_HOOK }}
