name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "content/**"
      - "i18n/i18next/zh/**"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Deploy site
        if: false
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.VERCEL_HOOK }}
          method: "GET"
      - name: Deploy site
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.RENDER_HOOK }}
          method: "GET"
