name: Build HN Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "content/**"
      - "i18n/i18next/zh/**"
      - "i18n/post-resource/zh/hn_--_reddit-top*.json"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/hn
          event-type: redeploy
