name: Build translate
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/actions/translate"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - run: npm install && npm run build:action
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .github/actions/translate/dist
